# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  registry:
    password: admin
  security:
    authentication:
      jwt:
        base64-secret: OTViY2Q4YjZlNzcwNmI4ZTY4NzFmNTNkOGU0YzFkYjNhZWYzYzUxOGJkNWQzYmI3YjJlMjc2NDRmODdjZDNiNjAwZTlkNWY1ODU1YWNkZjkwYzY5ODk0Y2YzYjdkMWUyOWE3YzBhMTFhZDZhYTg1ZGFjMjBjZWIwZTY4OGVhNTg=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterapp1
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
