package com.anderson.jhipsterapp1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFestaAllPropertiesEquals(Festa expected, Festa actual) {
        assertFestaAutoGeneratedPropertiesEquals(expected, actual);
        assertFestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFestaAllUpdatablePropertiesEquals(Festa expected, Festa actual) {
        assertFestaUpdatableFieldsEquals(expected, actual);
        assertFestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFestaAutoGeneratedPropertiesEquals(Festa expected, Festa actual) {
        assertThat(actual)
            .as("Verify Festa auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFestaUpdatableFieldsEquals(Festa expected, Festa actual) {
        assertThat(actual)
            .as("Verify Festa relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getTema()).as("check tema").isEqualTo(expected.getTema()))
            .satisfies(a -> assertThat(a.getValor()).as("check valor").isEqualTo(expected.getValor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFestaUpdatableRelationshipsEquals(Festa expected, Festa actual) {
        assertThat(actual)
            .as("Verify Festa relationships")
            .satisfies(a -> assertThat(a.getTipoFesta()).as("check tipoFesta").isEqualTo(expected.getTipoFesta()))
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()));
    }
}
