package com.anderson.jhipsterapp1.domain;

import static com.anderson.jhipsterapp1.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllPropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllUpdatablePropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoUpdatableFieldsEquals(expected, actual);
        assertPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAutoGeneratedPropertiesEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableFieldsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relevant properties")
            .satisfies(a -> assertThat(a.getDataPedido()).as("check dataPedido").isEqualTo(expected.getDataPedido()))
            .satisfies(a ->
                assertThat(a.getValorPedido())
                    .as("check valorPedido")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorPedido())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableRelationshipsEquals(Pedido expected, Pedido actual) {
        // empty method
    }
}
