package com.anderson.jhipsterapp1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoFestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoFestaAllPropertiesEquals(TipoFesta expected, TipoFesta actual) {
        assertTipoFestaAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoFestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoFestaAllUpdatablePropertiesEquals(TipoFesta expected, TipoFesta actual) {
        assertTipoFestaUpdatableFieldsEquals(expected, actual);
        assertTipoFestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoFestaAutoGeneratedPropertiesEquals(TipoFesta expected, TipoFesta actual) {
        assertThat(actual)
            .as("Verify TipoFesta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoFestaUpdatableFieldsEquals(TipoFesta expected, TipoFesta actual) {
        assertThat(actual)
            .as("Verify TipoFesta relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoFestaUpdatableRelationshipsEquals(TipoFesta expected, TipoFesta actual) {
        // empty method
    }
}
