# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTViY2Q4YjZlNzcwNmI4ZTY4NzFmNTNkOGU0YzFkYjNhZWYzYzUxOGJkNWQzYmI3YjJlMjc2NDRmODdjZDNiNjAwZTlkNWY1ODU1YWNkZjkwYzY5ODk0Y2YzYjdkMWUyOWE3YzBhMTFhZDZhYTg1ZGFjMjBjZWIwZTY4OGVhNTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
